package sensei0;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-00735fe6446b7f9f17dce574405a24dabe5e3f583c7585d5161835d7802417a9 */
/* JADX INFO: loaded from: classes.dex */
public final class bb {
    public int a;
    public final eb b;
    public final db c;
    public final cb d;
    public final fb e;
    public HashMap f;

    public bb() {
        eb ebVar = new eb();
        ebVar.a = 0;
        ebVar.b = 0;
        ebVar.c = 1.0f;
        ebVar.d = Float.NaN;
        this.b = ebVar;
        db dbVar = new db();
        dbVar.a = -1;
        dbVar.b = -1;
        dbVar.c = Float.NaN;
        dbVar.d = Float.NaN;
        this.c = dbVar;
        cb cbVar = new cb();
        cbVar.a = false;
        cbVar.d = -1;
        cbVar.e = -1;
        cbVar.f = -1.0f;
        cbVar.g = -1;
        cbVar.h = -1;
        cbVar.i = -1;
        cbVar.j = -1;
        cbVar.k = -1;
        cbVar.l = -1;
        cbVar.m = -1;
        cbVar.n = -1;
        cbVar.o = -1;
        cbVar.p = -1;
        cbVar.q = -1;
        cbVar.r = -1;
        cbVar.s = -1;
        cbVar.t = 0.5f;
        cbVar.u = 0.5f;
        cbVar.v = null;
        cbVar.w = -1;
        cbVar.x = 0;
        cbVar.y = 0.0f;
        cbVar.z = -1;
        cbVar.A = -1;
        cbVar.B = -1;
        cbVar.C = -1;
        cbVar.D = -1;
        cbVar.E = -1;
        cbVar.F = -1;
        cbVar.G = -1;
        cbVar.H = -1;
        cbVar.I = -1;
        cbVar.J = -1;
        cbVar.K = -1;
        cbVar.L = -1;
        cbVar.M = -1;
        cbVar.N = -1;
        cbVar.O = -1.0f;
        cbVar.P = -1.0f;
        cbVar.Q = 0;
        cbVar.R = 0;
        cbVar.S = 0;
        cbVar.T = 0;
        cbVar.U = -1;
        cbVar.V = -1;
        cbVar.W = -1;
        cbVar.X = -1;
        cbVar.Y = 1.0f;
        cbVar.Z = 1.0f;
        cbVar.a0 = -1;
        cbVar.b0 = 0;
        cbVar.c0 = -1;
        cbVar.g0 = false;
        cbVar.h0 = false;
        cbVar.i0 = true;
        this.d = cbVar;
        fb fbVar = new fb();
        fbVar.a = 0.0f;
        fbVar.b = 0.0f;
        fbVar.c = 0.0f;
        fbVar.d = 1.0f;
        fbVar.e = 1.0f;
        fbVar.f = Float.NaN;
        fbVar.g = Float.NaN;
        fbVar.h = 0.0f;
        fbVar.i = 0.0f;
        fbVar.j = 0.0f;
        fbVar.k = false;
        fbVar.l = 0.0f;
        this.e = fbVar;
        this.f = new HashMap();
    }

    public final void a(xa xaVar) {
        cb cbVar = this.d;
        xaVar.d = cbVar.g;
        xaVar.e = cbVar.h;
        xaVar.f = cbVar.i;
        xaVar.g = cbVar.j;
        xaVar.h = cbVar.k;
        xaVar.i = cbVar.l;
        xaVar.j = cbVar.m;
        xaVar.k = cbVar.n;
        xaVar.l = cbVar.o;
        xaVar.p = cbVar.p;
        xaVar.q = cbVar.q;
        xaVar.r = cbVar.r;
        xaVar.s = cbVar.s;
        ((ViewGroup.MarginLayoutParams) xaVar).leftMargin = cbVar.C;
        ((ViewGroup.MarginLayoutParams) xaVar).rightMargin = cbVar.D;
        ((ViewGroup.MarginLayoutParams) xaVar).topMargin = cbVar.E;
        ((ViewGroup.MarginLayoutParams) xaVar).bottomMargin = cbVar.F;
        xaVar.x = cbVar.N;
        xaVar.y = cbVar.M;
        xaVar.u = cbVar.J;
        xaVar.w = cbVar.L;
        xaVar.z = cbVar.t;
        xaVar.A = cbVar.u;
        xaVar.m = cbVar.w;
        xaVar.n = cbVar.x;
        xaVar.o = cbVar.y;
        xaVar.B = cbVar.v;
        xaVar.P = cbVar.z;
        xaVar.Q = cbVar.A;
        xaVar.E = cbVar.O;
        xaVar.D = cbVar.P;
        xaVar.G = cbVar.R;
        xaVar.F = cbVar.Q;
        xaVar.S = cbVar.g0;
        xaVar.T = cbVar.h0;
        xaVar.H = cbVar.S;
        xaVar.I = cbVar.T;
        xaVar.L = cbVar.U;
        xaVar.M = cbVar.V;
        xaVar.J = cbVar.W;
        xaVar.K = cbVar.X;
        xaVar.N = cbVar.Y;
        xaVar.O = cbVar.Z;
        xaVar.R = cbVar.B;
        xaVar.c = cbVar.f;
        xaVar.a = cbVar.d;
        xaVar.b = cbVar.e;
        ((ViewGroup.MarginLayoutParams) xaVar).width = cbVar.b;
        ((ViewGroup.MarginLayoutParams) xaVar).height = cbVar.c;
        String str = cbVar.f0;
        if (str != null) {
            xaVar.U = str;
        }
        xaVar.setMarginStart(cbVar.H);
        xaVar.setMarginEnd(cbVar.G);
        xaVar.a();
    }

    public final Object clone() {
        bb bbVar = new bb();
        cb cbVar = bbVar.d;
        cbVar.getClass();
        cb cbVar2 = this.d;
        cbVar.a = cbVar2.a;
        cbVar.b = cbVar2.b;
        cbVar.c = cbVar2.c;
        cbVar.d = cbVar2.d;
        cbVar.e = cbVar2.e;
        cbVar.f = cbVar2.f;
        cbVar.g = cbVar2.g;
        cbVar.h = cbVar2.h;
        cbVar.i = cbVar2.i;
        cbVar.j = cbVar2.j;
        cbVar.k = cbVar2.k;
        cbVar.l = cbVar2.l;
        cbVar.m = cbVar2.m;
        cbVar.n = cbVar2.n;
        cbVar.o = cbVar2.o;
        cbVar.p = cbVar2.p;
        cbVar.q = cbVar2.q;
        cbVar.r = cbVar2.r;
        cbVar.s = cbVar2.s;
        cbVar.t = cbVar2.t;
        cbVar.u = cbVar2.u;
        cbVar.v = cbVar2.v;
        cbVar.w = cbVar2.w;
        cbVar.x = cbVar2.x;
        cbVar.y = cbVar2.y;
        cbVar.z = cbVar2.z;
        cbVar.A = cbVar2.A;
        cbVar.B = cbVar2.B;
        cbVar.C = cbVar2.C;
        cbVar.D = cbVar2.D;
        cbVar.E = cbVar2.E;
        cbVar.F = cbVar2.F;
        cbVar.G = cbVar2.G;
        cbVar.H = cbVar2.H;
        cbVar.I = cbVar2.I;
        cbVar.J = cbVar2.J;
        cbVar.K = cbVar2.K;
        cbVar.L = cbVar2.L;
        cbVar.M = cbVar2.M;
        cbVar.N = cbVar2.N;
        cbVar.O = cbVar2.O;
        cbVar.P = cbVar2.P;
        cbVar.Q = cbVar2.Q;
        cbVar.R = cbVar2.R;
        cbVar.S = cbVar2.S;
        cbVar.T = cbVar2.T;
        cbVar.U = cbVar2.U;
        cbVar.V = cbVar2.V;
        cbVar.W = cbVar2.W;
        cbVar.X = cbVar2.X;
        cbVar.Y = cbVar2.Y;
        cbVar.Z = cbVar2.Z;
        cbVar.a0 = cbVar2.a0;
        cbVar.b0 = cbVar2.b0;
        cbVar.c0 = cbVar2.c0;
        cbVar.f0 = cbVar2.f0;
        int[] iArr = cbVar2.d0;
        if (iArr != null) {
            cbVar.d0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            cbVar.d0 = null;
        }
        cbVar.e0 = cbVar2.e0;
        cbVar.g0 = cbVar2.g0;
        cbVar.h0 = cbVar2.h0;
        cbVar.i0 = cbVar2.i0;
        db dbVar = bbVar.c;
        dbVar.getClass();
        db dbVar2 = this.c;
        dbVar2.getClass();
        dbVar.a = dbVar2.a;
        dbVar.b = dbVar2.b;
        dbVar.d = dbVar2.d;
        dbVar.c = dbVar2.c;
        eb ebVar = this.b;
        int i = ebVar.a;
        eb ebVar2 = bbVar.b;
        ebVar2.a = i;
        ebVar2.c = ebVar.c;
        ebVar2.d = ebVar.d;
        ebVar2.b = ebVar.b;
        fb fbVar = bbVar.e;
        fbVar.getClass();
        fb fbVar2 = this.e;
        fbVar2.getClass();
        fbVar.a = fbVar2.a;
        fbVar.b = fbVar2.b;
        fbVar.c = fbVar2.c;
        fbVar.d = fbVar2.d;
        fbVar.e = fbVar2.e;
        fbVar.f = fbVar2.f;
        fbVar.g = fbVar2.g;
        fbVar.h = fbVar2.h;
        fbVar.i = fbVar2.i;
        fbVar.j = fbVar2.j;
        fbVar.k = fbVar2.k;
        fbVar.l = fbVar2.l;
        bbVar.a = this.a;
        return bbVar;
    }
}
