package sensei0;

/* JADX INFO: compiled from: r8-map-id-00735fe6446b7f9f17dce574405a24dabe5e3f583c7585d5161835d7802417a9 */
/* JADX INFO: loaded from: classes.dex */
public abstract class gk0 {
    public static final g3 a;
    public static final g3 b;
    public static final g3 c;
    public static final g3 d;

    static {
        new g3(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new g3(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new g3(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new g3(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new g3(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new g3(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new g3(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new g3(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new g3(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new g3(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new g3(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new g3(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new g3(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new g3(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new g3(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new g3(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new g3(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new g3(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new g3(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new g3(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new g3(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        a = new g3(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        b = new g3(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new g3(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new g3(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        new g3(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new g3(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new g3(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        new g3(2, "WEB_MESSAGE_ARRAY_BUFFER", "WEB_MESSAGE_ARRAY_BUFFER");
        new g3(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new g3(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new g3(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new g3(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new g3(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new g3(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new g3(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new g3(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new g3(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        new ub0();
        new ub0();
        new ub0();
        new g3(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new ek0();
        new g3(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        c = new g3(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new g3(6, "FORCE_DARK", "FORCE_DARK");
        new g3(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        new g3(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new g3(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new g3(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new g3(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new g3(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new g3(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new g3(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
        new g3(2, "USER_AGENT_METADATA", "USER_AGENT_METADATA");
        new fk0(0, "MULTI_PROFILE", "MULTI_PROFILE");
        new g3(2, "ATTRIBUTION_REGISTRATION_BEHAVIOR", "ATTRIBUTION_BEHAVIOR");
        new g3(2, "WEBVIEW_MEDIA_INTEGRITY_API_STATUS", "WEBVIEW_INTEGRITY_API_STATUS");
        new g3(2, "MUTE_AUDIO", "MUTE_AUDIO");
        new g3(2, "WEB_AUTHENTICATION", "WEB_AUTHENTICATION");
        new g3(2, "SPECULATIVE_LOADING_STATUS", "SPECULATIVE_LOADING");
        new g3(2, "BACK_FORWARD_CACHE", "BACK_FORWARD_CACHE");
        new g3(2, "DELETE_BROWSING_DATA", "WEB_STORAGE_DELETE_BROWSING_DATA");
        new fk0(1, "PREFETCH_URL_V4", "PREFETCH_URL_V4");
        new g3(2, "IMPLEMENTATION_ONLY_FEATURE", "ASYNC_WEBVIEW_STARTUP");
        new g3(2, "DEFAULT_TRAFFICSTATS_TAGGING", "DEFAULT_TRAFFICSTATS_TAGGING");
        new g3(2, "PRERENDER_URL_V2", "PRERENDER_URL_V2");
        new g3(2, "SPECULATIVE_LOADING_CONFIG_V2", "SPECULATIVE_LOADING_CONFIG_V2");
        new g3(2, "SAVE_STATE", "SAVE_STATE");
        new g3(2, "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE", "WEB_VIEW_NAVIGATION_CLIENT_BASIC_USAGE");
        new g3(2, "CACHE_PROVIDER", "PROVIDER_WEAKLY_REF_WEBVIEW");
        d = new g3(2, "PAYMENT_REQUEST", "PAYMENT_REQUEST");
        new g3(2, "WEBVIEW_BUILDER", "WEBVIEW_BUILDER");
    }
}
